name: CocoaPods Lint

on:
  push:
    paths:
      - "ScrollFlowLabel.podspec"
      - "Gemfile.lock"
      - ".github/workflows/pod_lint.yml"

jobs:
  pod_lint:
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: '3.1'

    - name: Lint
      run: bundle exec pod lib lint ScrollFlowLabel.podspec
