name: SwiftLint

on: pull_request

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Apple-Actions/action-swiftlint@409825d
      with:
        reporter: github-pr-review
        level: warning
