name: SwiftLint

on: pull_request

jobs:
  swiftlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Apple-Actions/action-swiftlint@409825dd1361e188f6717494101ab7b49b29453d
      with:
        reporter: github-pr-review
        level: warning
